In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [16]:
#model.fit(X,Y)

In [17]:
X = pd.read_csv('Train.csv')

In [18]:
X.head()


feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [19]:
m=X.shape[0]
ones = np.ones((X.shape[0],1))

In [20]:
target = []
for i in range(m):
    target.append(X["target"][i])

In [21]:
target = np.array(target)

In [22]:
target.shape

(1600,)

In [23]:
target = np.transpose(target)

In [24]:
target.shape

(1600,)

In [25]:
target

array([ -82.15466656,  -48.89796018,   77.2703707 , ..., -107.51050797,
        -47.34155781, -115.93900296])

In [37]:
X_train = []

In [38]:
for i in range(m):
    temp = []
    temp.append(X["feature_1"][i])
    temp.append(X["feature_2"][i])
    temp.append(X["feature_3"][i])
    temp.append(X["feature_4"][i])
    temp.append(X["feature_5"][i])
    X_train.append(temp)

In [41]:
X_train = np.array(X_train)
target = np.array(target)

In [64]:
print(X_train.shape)
print(target.shape)

(1600, 5)
(1600,)


In [43]:
#Training of data

In [65]:
model = LinearRegression() 

In [66]:
model.fit(X_train,target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
model.coef_

array([29.68187118, 92.66247759,  8.28062089, 44.76773522,  2.51916121])

In [68]:
model.intercept_

4.990966735574961

In [69]:
X_train[0]

array([ 0.29341624, -0.94559871, -0.42110515,  0.40681602,  0.52566183])

In [70]:
model.predict([X_train[1]])

array([-89.46019557])

In [95]:
X2 = pd.read_csv('test.csv')

In [96]:
X2.head()

feature_1  feature_2  feature_3  feature_4  feature_5
0   1.015254   2.076209  -0.266435  -2.418088  -0.980503
1  -0.375021   0.953185   0.626719   0.704406  -0.355489
2  -1.024452   0.962991  -0.407942  -1.861274   0.455201
3  -2.489841   0.544802   0.601219  -0.607021  -1.314286
4  -0.384675  -0.833624   1.358552  -0.547932   0.411925

In [107]:
X_test = []
X2.shape[0]

400

In [108]:
for i in range(X2.shape[0]):
    temp = []
    temp.append(X2["feature_1"][i])
    temp.append(X2["feature_2"][i])
    temp.append(X2["feature_3"][i])
    temp.append(X2["feature_4"][i])
    temp.append(X2["feature_5"][i])
    X_test.append(temp)

In [117]:
Y=model.predict(X_test)

In [118]:
print(Y.shape[0])
model.score(X_train,target)
id1=[]
for i in range(Y.shape[0]):
    id1.append(i)


400


In [119]:
dict = {'Id': id1, 'target': Y}  
df = pd.DataFrame(dict)
df.to_csv('ans.csv',index=False)